# config.yml (Relevant Sections Only)

economic:
  interval:
    days_2: 7  # Upkeep every 7 days 
    time: '23:00:00' # Time of day for upkeep collection - AS DESIRED
    change-cooldown_time: 0.1d # Cooldown for changing tax/upkeep - KEEP AS DESIRED

upkeep:
  per-chunk: 0.214  
  unclaim: false     # Disables automatic chunk unclaiming if upkeep not paid 
  nopay_time: 7d    # 7 day grace period for newly created Lands 
  upkeep-reminder_time: 1h # Land member reminder frequency - KEEP AS DESIRED

chunk:
  costs_2: 5.0    

economy:
    vault:
      enabled_10: true 
